--- 
apiVersion: extensions/v1beta1
kind: StatefulSet #Deployment
metadata:
  name: percona-xtradb-cluster
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: percona-xtradb-cluster
    spec:
      containers: 
      - name: percona-xtradb-cluster
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: Theistareyk
        - name: DISCOVERY_SERVICE
          value: "10.99.0.10:2379"
        - name: CLUSTER_NAME
          value: k8scluster2
        - name: XTRABACKUP_PASSWORD
          value: Theistare
        image: "perconalab/percona-xtradb-cluster"
        ports: 
        - containerPort: 3306
        - containerPort: 4567
        - containerPort: 4568
        volumeMounts: 
        - name: perconastorageclaim
          mountPath: /var/lib/mysql
      volumes: 
       - name: perconastorageclaim
         emptyDir: {}
         #persistentVolumeClaim: 
         #  claimName: perconastorageclaim
  volumeClaimTemplates:
  - metadata:
      name: perconastorageclaim
      annotations:
        volume.alpha.kubernetes.io/storage-class: "perconastorageclaim"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 200Gi