apiVersion: v1
kind: ReplicationController
metadata:
 name: proxysql-rc
spec:
  replicas: 1 # tells deployment to run N pods matching the template
  selector:
    front: proxysql
  template: # create pods using pod definition in this template
    metadata:
     name: proxysql
     labels:
       app: pxc-app
       front: proxysql
    spec:
      containers:
      - name: proxysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Theistareyk"
        - name: DISCOVERY_SERVICE
          value: "10.99.0.10:2379"
        - name: CLUSTER_NAME
          value: "k8scluster2"
        - name: MYSQL_PROXY_USER
          value: "proxyuser"
        - name: MYSQL_PROXY_PASSWORD
          value: "s3cret"
        image: perconalab/proxysql
        ports:
        - containerPort: 3306
        - containerPort: 6032
    