apiVersion: v1
kind: Service
metadata: 
  name: haproxy
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30081
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: haproxy