apiVersion: v1
kind: Service
metadata: 
  name: quassel-core
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 4242
      protocol: TCP
      nodePort: 30001
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: quassel-core