apiVersion: v1
kind: PersistentVolume
metadata:
  name: PerconaStorageClaim
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.99.0.10
path: "/nfs-shares/PerconaCluster"