apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: setkeh-com-haproxy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: setkeh/haproxy-docker
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: haproxystorage
          mountPath: /usr/local/etc/haproxy
      volumes:
      - name: haproxystorage
        persistentVolumeClaim:
          claimName: haproxystorage