version: '3'

services:
  drone-server:
    image: drone/drone:latest
    ports:
      - 80:8000
    volumes:
      - /storage/Drone:/var/lib/drone/
    restart: on-failure
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://drone.home.setkeh.com:8000
      - DRONE_ADMIN=setkeh
      - DRONE_GITHUB=true
      - DRONE_ORGS=thesetkehproject
      - DRONE_GITHUB_CLIENT=7b8beee5905c49422d76
      - DRONE_GITHUB_SECRET=dba140c8832c63f843e4f661b7db01043c24200a
      - DRONE_SECRET=DroneSecret

  drone-agent:
    image: drone/drone:latest
    command: agent
    restart: on-failure
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=DroneSecret
