version: '3'

services:
  registry-server:
    image: registry:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 5000:5000
    volumes:
      - /storage/registry-images/:/var/lib/registry
      - /etc/letsencrypt/live/registry.setkeh.com:/certs
    environment:
      - SEARCH_BACKEND=sqlalchemy
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/cert.pem
      - REGISTRY_HTTP_TLS_KEY=/certs/privkey.pem

  registry-ui:
    image: hyper/docker-registry-web:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - registry-server
    ports:
      - 8080:8080
    links:
      - registry-server:registry-server
    environment:
      - REGISTRY_URL=https://registry-server:5000/v2
      - REGISTRY_NAME=registry.setkeh.com:5000